# Generated by Django 6.0.2 on 2026-02-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abuneci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-poct')),
                ('tarix', models.DateTimeField(auto_now_add=True, verbose_name='Abune tarixi')),
            ],
            options={
                'verbose_name': 'Abuneci',
                'verbose_name_plural': 'Abuneciler',
                'ordering': ['-tarix'],
            },
        ),
        migrations.CreateModel(
            name='ElaqeMesaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-poct')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('tarix', models.DateTimeField(auto_now_add=True, verbose_name='Gonderilme tarixi')),
                ('oxunub', models.BooleanField(default=False, verbose_name='Oxunub')),
            ],
            options={
                'verbose_name': 'Elaqe mesaji',
                'verbose_name_plural': 'Elaqe mesajlari',
                'ordering': ['-tarix'],
            },
        ),
    ]
